# Generated by Django 5.2.9 on 2025-12-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='card',
            name='notes',
        ),
    ]
