# Generated by Django 5.2.9 on 2025-12-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_deck_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studylog',
            table='api_study_log',
        ),
    ]
